PycharmProjects/pythonProject3/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('notebook/', include('notebook.urls', namespace='notebook')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from blog.apps import BlogConfig
from blog.views import (
    ArticleListView, ArticleDetailView, ArticleCreateView, ArticleUpdateView, ArticleDeleteView
)

from django.urls import path

app_name = BlogConfig.name

urlpatterns = [
    path('articles/', ArticleListView.as_view(), name='article_list'),
    path('articles/<int:pk>/', ArticleDetailView.as_view(), name='article_detail'),
    path('create_article/', ArticleCreateView.as_view(), name='article_create'),
    path('update_article/<int:pk>/', ArticleUpdateView.as_view(), name='article_update'),
    path('delete_article/<int:pk>/', ArticleDeleteView.as_view(), name='article_delete'),
]

mailing_service/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailings.urls', namespace='mailings')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

mailings/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mailings.apps import MailingsConfig
from mailings.views import (
    IndexView, MailingListView, MailingDetailView, MailingCreateView,
    MailingUpdateView, MailingDeleteView, ChangeMailingStatusView, ClientListView,
    ClientDetailView, ClientCreateView, ClientUpdateView, ClientDeleteView,
    MailingLogsListView, ManagerMailingListView
)

app_name = MailingsConfig.name

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('mailings/', MailingListView.as_view(), name='mailing_list'),
    path('mailings/<slug:slug>/', MailingDetailView.as_view(), name='mailing_detail'),
    path('mailing_create/', MailingCreateView.as_view(), name='mailing_create'),
    path('mailing_update/<slug:slug>/', MailingUpdateView.as_view(), name='mailing_update'),
    path('mailing_delete/<slug:slug>/', MailingDeleteView.as_view(), name='mailing_delete'),
    path('status_change/<slug:slug>/', ChangeMailingStatusView.as_view(), name='mailing_status'),
    path('clients/', ClientListView.as_view(), name='client_list'),
    path('clients/<int:pk>/', cache_page(900)(ClientDetailView.as_view()), name='client_detail'),
    path('client_create/', ClientCreateView.as_view(), name='client_create'),
    path('client_update/<int:pk>/', ClientUpdateView.as_view(), name='client_update'),
    path('client_delete/<int:pk>/', ClientDeleteView.as_view(), name='client_delete'),
    path('mailing_logs/', MailingLogsListView.as_view(), name='mailing_logs_list'),
    path('manager_mailing/', ManagerMailingListView.as_view(), name='manager_mailing_list'),
]

urls.py
from django.urls import path

from dogs.apps import DogsConfig
from dogs.views import index, categories, category_dogs

app_name = DogsConfig.name

urlpatterns = [
    path('', index, name='index'),
    path('categories/', categories, name='categories'),
    path('<int:pk>/dogs/', category_dogs, name='category_dogs')
]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from django.views.decorators.cache import cache_page

from users.apps import UsersConfig
from users.views import (
    UserRegisterView, UserLoginView, UserSentConfirmEmail, UserConfirmEmailView,
    UserConfirmedEmail, UserFailConfirmEmail, UserPasswordResetView, UserSentPassword,
    UserListView, UserChangeActive, UserDetailView
)

app_name = UsersConfig.name

urlpatterns = [
    path('', UserListView.as_view(), name='user_list'),
    path('user/<int:pk>/', UserDetailView.as_view(), name='user_detail'),
    path('register/', UserRegisterView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('sent_confirm_email/', cache_page(3600)(UserSentConfirmEmail.as_view()), name='email_sent_confirm'),
    path('confirm_email/<str:uidb64>/<str:token>/', UserConfirmEmailView.as_view(), name='email_confirm'),
    path('confirmed_email/', cache_page(3600)(UserConfirmedEmail.as_view()), name='email_confirmed'),
    path('fail_confirm_email/', cache_page(3600)(UserFailConfirmEmail.as_view()), name='email_fail_confirm'),
    path('password_reset/', UserPasswordResetView.as_view(), name='password_reset'),
    path('password_sent_email/', cache_page(3600)(UserSentPassword.as_view()), name='password_sent_email'),
    path('change_active/<int:pk>/', UserChangeActive.as_view(), name='user_change_active'),
]

mailings/forms.py
from datetime import datetime

from django import forms

from mailings.models import Mailing, Client


class MailingForm(forms.ModelForm):
    '''
    Форма рассылки сервиса
    '''

    class Meta:
        model = Mailing
        fields = ('title', 'body', 'sending_time', 'regularity',)
        widgets = {'sending_time': forms.DateTimeInput(attrs={'type': 'datetime-local'})}

    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self.fields['sending_time'].help_text = 'Рассылка должна быть опубликована не ранее, ' \
                                                'чем через минуту от текущего времени.'

    def clean_sending_time(self) -> datetime:
        cleaned_data = self.cleaned_data['sending_time']

        if cleaned_data.timestamp() <= datetime.now().timestamp():
            raise forms.ValidationError('Рассылка должна иметь достоверное время')

        return cleaned_data


class ClientForm(forms.ModelForm):
    '''
    Форма клиента сервиса
    '''

    class Meta:
        model = Client
        fields = ('fullname', 'email', 'comment',)

    def __init__(self, *args, **kwargs) -> None:
        self.user = kwargs.pop('user')
        self.email = kwargs.pop('email')

        super().__init__(*args, **kwargs)

    def clean_email(self) -> str:
        cleaned_data = self.cleaned_data['email']

        if cleaned_data != self.email:
            is_existed = Client.objects.filter(email=cleaned_data, user=self.user).exists()

            if is_existed:
                raise forms.ValidationError('Пользователь с таким e-mail существует!')

        return cleaned_data

mailings/views.py
import random

from django.contrib.auth.mixins import (
    LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
)
from django.db.models import Q, QuerySet
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import (
    CreateView, DeleteView, DetailView, ListView, TemplateView, UpdateView
)

from typing import Any

from pytils.translit import slugify

from mailings.forms import ClientForm, MailingForm
from mailings.models import Client, Mailing, MailingLogs, MailingStatus
from mailings.services import (
    check_mailing_status, check_user, get_articles_from_cache, get_status_object
)


class IndexView(TemplateView):
    '''
    Класс отображения главной страницы сервиса
    '''
    template_name = 'mailings/index.html'

    def get_context_data(self, **kwargs) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['title'] = 'Главная страница'
        context['total_mailings'] = len(Mailing.objects.all())
        context['active_mailings'] = len(Mailing.objects.exclude(status=get_status_object('завершена')))
        context['unique_clients'] = len(Client.objects.values('email').distinct())
        try:
            context['blog_articles'] = random.sample(list(get_articles_from_cache()), 3)
        except ValueError:
            context['blog_articles'] = []

        return context


class MailingListView(LoginRequiredMixin, UserPassesTestMixin, PermissionRequiredMixin, ListView):
    '''
    Класс отображения страницы со всеми рассылками
    '''
    model = Mailing
    permission_required = 'mailings.view_mailing'

    def get_queryset(self, *args, **kwargs) -> QuerySet:
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(user=self.request.user)

        return queryset

    def get_context_data(self, **kwargs) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['title'] = 'Рассылки'

        return context

    def test_func(self) -> bool:
        return self.request.user.groups.filter(name='service_users')


class MailingDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    '''
    Класс для отображения информации об одной рассылке
    '''
    model = Mailing
    permission_required = 'mailings.view_mailing'

    def dispatch(self, request, *args, **kwargs) -> HttpResponse:
        group = self.request.user.groups.filter(name='manager')
        status = self.get_object().status

        if not group:
            if not check_user(self.get_object().user, self.request.user):
                return redirect('mailings:mailing_list')
        else:
            if status == get_status_object('завершена'):
                return redirect('mailings:manager_mailing_list')

        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['title'] = self.object.title

        return context


class MailingCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    '''
    Класс для создания рассылки
    '''
    model = Mailing
    form_class = MailingForm
    permission_required = 'mailings.add_mailing'
    success_url = reverse_lazy('mailings:mailing_list')

    def form_valid(self, form) -> HttpResponse:
        if form.is_valid():
            self.object = form.save()
            self.object.status = MailingStatus.objects.get(name='создана')
            self.object.slug = slugify(f'{self.object.title}-{self.object.pk}')
            self.object.user = self.request.user
            self.object.save()

        return super().form_valid(form)

    def get_context_data(self, **kwargs) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['title'] = 'Создание рассылки'

        return context


class MailingUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    '''
    Класс для редактирования рассылки
    '''
    model = Mailing
    form_class = MailingForm
    permission_required = 'mailings.change_mailing'
    success_url = reverse_lazy('mailings:mailing_list')

    def dispatch(self, request, *args, **kwargs) -> HttpResponse:
        mailing = self.get_object()

        if not check_user(mailing.user, self.request.user) or not check_mailing_status(mailing, 'создана'):
            return redirect('mailings:mailing_list')

        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form) -> HttpResponse:
        if form.is_valid():
            self.object = form.save()
            self.object.slug = slugify(f'{self.object.title}-{self.object.pk}')
            self.object.save()

        return super().form_valid(form)

    def get_context_data(self, **kwargs) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['title'] = f'Редактирование рассылки {self.object.title}'

        return context


class MailingDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    '''
    Класс для удаления рассылки
    '''
    model = Mailing
    permission_required = 'mailings.delete_mailing'

    def dispatch(self, request, *args, **kwargs) -> HttpResponse:
        mailing = self.get_object()
        group = self.request.user.groups.filter(name='manager')

        if not group:
            if not check_user(mailing.user, self.request.user) or check_mailing_status(mailing, 'запущена'):
                return redirect('mailings:mailing_list')
        elif self.get_object().status != get_status_object('создана'):
            return redirect('mailings:manager_mailing_list')

        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self) -> str:
        group = self.request.user.groups.filter(name='manager')

        if group:
            return reverse('mailings:manager_mailing_list')

        return reverse('mailings:mailing_list')

    def get_context_data(self, **kwargs) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['title'] = f'Удаление рассылки {self.object.title}'

        return context


class ChangeMailingStatusView(LoginRequiredMixin, PermissionRequiredMixin, View):
    '''
    Класс для перевода рассылки к типу "завершена"
    '''
    permission_required = 'mailings.change_mailingstatus'

    def __get_mailing(self, slug) -> Mailing:
        mailing = get_object_or_404(Mailing, slug=slug)

        return mailing

    def get(self, request, slug) -> HttpResponse:
        mailing = self.__get_mailing(slug)
        group = self.request.user.groups.filter(name='manager')

        if not group:
            if not check_user(mailing.user, self.request.user) or not check_mailing_status(mailing, 'запущена'):
                return redirect('mailings:mailing_list')
        elif not check_mailing_status(mailing, 'запущена'):
            return redirect('mailings:manager_mailing_list')

        return render(
            request, 'mailings/mailing_status_change.html',
            {'object': mailing, 'title': 'Изменение статуса'}
        )

    def post(self, request, slug) -> HttpResponse:
        mailing = self.__get_mailing(slug)
        mailing.status = MailingStatus.objects.get(name='завершена')
        mailing.save()

        group = self.request.user.groups.filter(name='manager')

        if group:
            return redirect('mailings:manager_mailing_list')

        return redirect('mailings:mailing_list')


class ClientListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    '''
    Класс для отображения всех клиентов
    '''
    model = Client
    permission_required = 'mailings.view_client'

    def get_queryset(self, *args, **kwargs) -> QuerySet:
        queryset = super().get_queryset(*args, **kwargs)
        user = self.request.user
        queryset = queryset.filter(user=user)

        return queryset

    def get_context_data(self, **kwargs) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['title'] = 'Клиенты'

        return context


class ClientDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    '''
    Класс для отображения одного клиента
    '''
    model = Client
    permission_required = 'mailings.view_client'

    def dispatch(self, request, *args, **kwargs) -> HttpResponse:
        if not check_user(self.get_object().user, self.request.user):
            return redirect('mailings:client_list')

        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['title'] = self.object.fullname

        return context


class ClientCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    '''
    Класс для создания клиента
    '''
    model = Client
    form_class = ClientForm
    permission_required = 'mailings.add_client'
    success_url = reverse_lazy('mailings:client_list')

    def get_form_kwargs(self) -> dict[str, Any]:
        kwargs = super().get_form_kwargs()
        kwargs.update({'user': self.request.user, 'email': None})

        return kwargs

    def form_valid(self, form) -> HttpResponse:
        if form.is_valid():
            self.object = form.save()
            self.object.user = self.request.user
            self.object.save()

        return super().form_valid(form)

    def get_context_data(self, **kwargs) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['title'] = 'Создание клиента'

        return context


class ClientUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    '''
    Класс для обновления клиента
    '''
    model = Client
    form_class = ClientForm
    permission_required = 'mailings.change_client'

mailings/templates/mailings/base.html
{% load static %}
<!doctype html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">
    <title>{{ title }}</title>
</head>
<body>
{% include 'mailings/includes/inc_main_menu.html' %}
{% block content %}
{% endblock %}
{% include 'mailings/includes/inc_footer.html' %}
</body>
</html>

mailings/templates/mailings/client_detail.html
{% extends 'mailings/base.html' %}

{% block content %}

<div class="container">
    <div class="row">
        <h1 class="mt-2 text-center">ИНФОРМАЦИЯ О КЛИЕНТ</h1>
        <div class="card mt-2">
            <h3 class="p-1">Полное имя: {{ object.fullname|title }}</h3>
            <h3 class=" p-1">E-mail адрес: {{ object.email }} </h3>
            <hr>
            <p class=""><b>Комментарий: </b>{{ object.comment }}</p>
            <hr>
            <div class="col-5 mb-3">
                <div class="row">
                    <div class="col-3">
                        <a href="{% url 'mailings:client_update' object.id %}"
                           class="btn btn-outline-dark ">РЕДАКТИРОВАТЬ</a>
                    </div>
                    <div class="col-2 ms-4">
                        <a href="{% url 'mailings:client_delete' object.id %}"
                           class="btn btn-outline-dark">УДАЛИТЬ</a>
                    </div>
                    <div class="col-2">
                        <a href="{% url 'mailings:client_list' %}" class="btn btn-outline-dark ms-5">НАЗАД</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

mailings/templates/mailings/client_list.html
{% extends 'mailings/base.html' %}

{% block content %}
<div class="container text-center mt-5 mb-5">
    <h1 class="mt-5">КЛИЕНТЫ</h1>
    <div class="row">
        <div class="col-2 text-start"><a href="{% url 'mailings:client_create' %}"
                                         class="btn btn-dark">+ КЛИЕНТ</a></div>
    </div>
    <div class="row mt-2">
        {% for object in object_list %}
            <div class="col-3">
                <a href="{% url 'mailings:client_detail' object.pk %}" class="link-light">
                    <div class="card text-white bg-dark mb-3" style="max-width: 18rem;">
                        <div class="card-header">{{ object.email }}</div>
                        <div class="card-body">
                            <h5 class="card-title">{{ object.fullname }}</h5>
                            <hr>
                            <a href="{% url 'mailings:client_update' object.id%}" type="button"
                               class="btn btn-dark">Обновить</a>
                            <a href="{% url 'mailings:client_delete' object.id%}" type="button"
                               class="btn btn-dark">Удалить</a>
                        </div>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

mailings/templates/mailings/mailing_detail.html
{% extends 'mailings/base.html' %}
{% load custom_tags %}

{% block content %}

<div class="container">
    <div class="row">
        {% if object.status.name == 'завершена' %}
            <h1 class="mt-2 text-center">РАССЫЛКА(ЗАВЕРШЕНА)</h1>
            <div class="card mt-2">
                <h1 class="text-muted p-1">{{ object.title|upper }}</h1>
                <hr>
                <p class="text-muted">{{ object.body }} </p>
                <hr>
                <p class="text-muted"><b>Периодичность: </b>{{ object.regularity }}</p>
                <p class="text-muted"><b>Время отправки: </b>{{ object.sending_time }}</p>
                <div class="col-5 mb-3">
                    <div class="row">
                        <div class="col-2">
                            <a href="{% url 'mailings:mailing_delete' object.slug %}"
                               class="btn btn-danger">УДАЛИТЬ</a>
                        </div>
                        <div class="col-2">
                            <a href="{% url 'mailings:mailing_list' %}" class="btn btn-success ms-5">НАЗАД</a>
                        </div>
                    </div>
                </div>
            </div>
        {% else %}
            <h1 class="mt-2 text-center">РАССЫЛКА</h1>
            <div class="card mt-2">
                <h1 class="p-1">{{ object.title|upper }}</h1>
                <hr>
                <p>{{ object.body }} </p>
                <hr>
                {% if object.regularity %}
                    <p><b>Переодичность: </b>{{ object.regularity }}</p>
                {% else %}
                    <p><b>Переодичность: </b>Не указана</p>
                {% endif %}
                <p><b>Время отправки: </b>{{ object.sending_time }}</p>
                {% if user|has_group:"manager" %}
                    <p ><b>
                        Пользователь:
                        <a class="text-dark" href="{% url 'users:user_detail' object.user.pk %}">{{ object.user.email }}</a>
                    </b></p>
                {% endif %}
                <div class="row">
                    {% if object.status.name == 'создана' %}
                        {% if user|has_group:"manager" %}
                            <div class="row">
                                <div class="col-9"></div>
                                <div class="col-1 text-end">
                                    <a href="{% url 'mailings:mailing_delete' object.slug %}"
                                       class="btn btn-outline-dark">УДАЛИТЬ</a>
                                </div>
                                <div class="col-2 text-end">
                                    <a href="{% url 'users:user_change_active' object.user.id%}" type="button"
                                       class="btn btn-outline-dark mb-2">ЗАБЛОКИРОВАТЬ</a>
                                </div>
                            </div>
                        {% else %}
                            <div class="col-1 text-start">
                                <a href="{% url 'mailings:mailing_update' object.slug %}" class="btn btn-primary">
                                    РЕДАКТИРОВАТЬ
                                </a>
                            </div>
                            <div class="col-2 text-start">
                                <a href="{% url 'mailings:mailing_delete' object.slug %}"
                                   class="btn btn-danger ms-5 ">УДАЛИТЬ</a>
                            </div>
                            <div class="col-2 text-start mb-3">
                                <a href="{% url 'mailings:mailing_list' %}" class="btn btn-success">НАЗАД</a>
                            </div>
                        {% endif %}
                    {% else %}
                        {% if user|has_group:"manager" %}
                            <div class="row">
                                <div class="col-9"></div>
                                <div class="col-1 text-end">
                                    <a href="{% url 'mailings:mailing_status' object.slug %}"
                                       class="btn btn-outline-dark">ЗАВЕРШИТЬ</a>
                                </div>
                                <div class="col-2 text-end">
                                    <a href="{% url 'users:user_change_active' object.user.id%}" type="button"
                                       class="btn btn-outline-dark mb-2">ЗАБЛОКИРОВАТЬ</a>
                                </div>
                            </div>
                        {% else %}
                            <div class="row">
                                <div class="col-1 text-start">
                                    <a href="{% url 'mailings:mailing_status' object.slug %}"
                                       class="btn btn-danger">ЗАВЕРШИТЬ</a>
                                </div>
                                <div class="col-1 text-start">
                                    <a href="{% url 'mailings:mailing_list' %}" class="btn btn-success mb-3 ms-4">
                                        НАЗАД
                                    </a>
                                </div>
                            </div>
                        {% endif %}
                    {% endif %}
                </div>
            </div>
        {% endif %}
    </div>
</div>
{% endblock %}

mailings/templates/mailings/mailing_list.html
{% extends 'mailings/base.html' %}

{% block content %}

<div class="container text-center mt-5 mb-5">
    <h1 class="mt-5">ЗАПЛАНИРОВАННЫЕ</h1>
    <div class="row">
        <div class="col-2 text-start"><a href="{% url 'mailings:mailing_create' %}"
                                         class="btn btn-success">+ РАССЫЛКА</a></div>
        <div class="col-9"></div>
        <div class="col-1">
            <a href="{% url 'mailings:mailing_logs_list' %}" class="btn btn-dark">ЛОГИ</a>
        </div>
    </div>
    <div class="row">
        {% for object in object_list %}
            {% if object.status.name == "создана" %}
                <div class="col-sm-4 mb-3 mb-sm-0">
                    <div class="card mt-2">
                        <a href="{% url 'mailings:mailing_detail' object.slug %}"
                           class="link-dark">
                            <div class="card-body">
                                <h5 class="card-title">{{ object.title|upper }}</h5>
                                <p class="card-text text-start">{{ object.body|slice:":100" }}...</p>
                                <p class="card-text text-start"><b>Время отправки: </b>{{ object.sending_time }}</p>
                                {% if object.regularity %}
                                    <p class="card-text text-start"><b>Периодичность: </b>{{ object.regularity }}</p>
                                {% else %}
                                    <p class="card-text text-start"><b>Периодичность: </b>Не указана</p>
                                {% endif %}
                                <div class="row">
                                    <div class="col-5">
                                        <a href="{% url 'mailings:mailing_update' object.slug %}"
                                           class="btn btn-primary mt-4 ">РЕДАКТИРОВАТЬ</a>
                                    </div>
                                    <div class="col-2">
                                        <a href="{% url 'mailings:mailing_delete' object.slug %}"
                                           class="btn btn-danger mt-4 ">УДАЛИТЬ</a>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    </div>
</div>
<div class="container text-center mt-5 mb-5">
    <h1 class="mt-5">ЗАПУЩЕННЫЕ</h1>
    <div class="row">
        {% for object in object_list %}
            {% if object.status.name == "запущена" %}
                <div class="col-sm-4 mb-3 mb-sm-0 ">
                    <div class="card mt-2">
                        <a href="{% url 'mailings:mailing_detail' object.slug %}"
                           class="link-dark">
                            <div class="card-body mt-2">
                                <h5 class="card-title">{{ object.title|upper }}</h5>
                                <p class="card-text text-start">{{ object.body|slice:":100" }}...</p>
                                <p class="card-text text-start"><b>Время отправки: </b>{{ object.sending_time }}</p>
                                <p class="card-text text-start"><b>Периодичность: </b>{{ object.regularity }}</p>
                                <div class="row">
                                    <div class="col-2">
                                        <a href="{% url 'mailings:mailing_status' object.slug %}"
                                           class="btn btn-danger mt-2 ">ЗАВЕРШИТЬ</a>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    </div>
</div>
<div class="container text-center mt-5 mb-5">
    <h1 class="mt-5">ЗАВЕРШЕННЫЕ</h1>
    <div class="row">
        {% for object in object_list %}
            {% if object.status.name == "завершена" %}
                <div class="col-sm-4 mb-3 mb-sm-0">
                    <div class="card mt-2">
                        <a href="{% url 'mailings:mailing_detail' object.slug %}"
                           class="link-dark">
                            <div class="card-body">
                                <h5 class="card-title text-muted">{{ object.title|upper }}</h5>
                                <p class="card-text text-start text-muted">{{ object.body|slice:":100" }}...</p>
                                <p class="card-text text-start text-muted"><b>Время отправки:
                                </b>{{ object.sending_time }}
                                </p>
                                {% if object.regularity %}
                                    <p class="card-text text-start text-muted">
                                        <b>Периодичность: </b>{{ object.regularity }}
                                    </p>
                                {% else %}
                                    <p class="card-text text-start text-muted"><b>Периодичность: </b>Не указана</p>
                                {% endif %}
                                <div class="row">
                                    <div class="col-2">
                                        <a href="{% url 'mailings:mailing_delete' object.slug %}"
                                           class="btn btn-danger mt-2 ">УДАЛИТЬ</a>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    </div>
</div>
{% endblock %}