PycharmProjects/pythonProject3/catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page, never_cache

from catalog.apps import CatalogConfig
from catalog.views import con, IndexView, CategoryListView, ProductListView, ProductCreateView, ProductUpdateView, ProductDeleteView

app_name = CatalogConfig.name

urlpatterns = [
    path('', cache_page(IndexView.as_view()), name='home'),
    path('categories/', CategoryListView.as_view(), name='categories'),
    path('contacts/', con),
    path('<int:pk>/products/', ProductListView.as_view(), name='products'),
    path('products/create/', ProductCreateView.as_view(), name='product_create'),
    path('products/update/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
    path('products/delete/<int:pk>/', never_cache(ProductDeleteView.as_view()), name='product_delete'),
]

PycharmProjects/pythonProject3/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('notebook/', include('notebook.urls', namespace='notebook')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PycharmProjects/pythonProject3/notebook/urls.py
from django.urls import path

from notebook.apps import NotebookConfig
from notebook.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = NotebookConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>', BlogDetailView.as_view(), name='view'),
    path('edit/<int:pk>', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>', BlogDeleteView.as_view(), name='delete'),
]

PycharmProjects/pythonProject3/users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView, UserUpdateView, generate_new_password

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', UserUpdateView.as_view(), name='profile'),
    path('profile/genpassword/', generate_new_password, name='generate_new_password'),
]

mailing_service/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailings.urls', namespace='mailings')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

urls.py
from django.urls import path

from dogs.apps import DogsConfig
from dogs.views import index, categories, category_dogs

app_name = DogsConfig.name

urlpatterns = [
    path('', index, name='index'),
    path('categories/', categories, name='categories'),
    path('<int:pk>/dogs/', category_dogs, name='category_dogs')
]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from django.views.decorators.cache import cache_page

from users.apps import UsersConfig
from users.views import (
    UserRegisterView, UserLoginView, UserSentConfirmEmail, UserConfirmEmailView,
    UserConfirmedEmail, UserFailConfirmEmail, UserPasswordResetView, UserSentPassword,
    UserListView, UserChangeActive, UserDetailView
)

app_name = UsersConfig.name

urlpatterns = [
    path('', UserListView.as_view(), name='user_list'),
    path('user/<int:pk>/', UserDetailView.as_view(), name='user_detail'),
    path('register/', UserRegisterView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('sent_confirm_email/', cache_page(3600)(UserSentConfirmEmail.as_view()), name='email_sent_confirm'),
    path('confirm_email/<str:uidb64>/<str:token>/', UserConfirmEmailView.as_view(), name='email_confirm'),
    path('confirmed_email/', cache_page(3600)(UserConfirmedEmail.as_view()), name='email_confirmed'),
    path('fail_confirm_email/', cache_page(3600)(UserFailConfirmEmail.as_view()), name='email_fail_confirm'),
    path('password_reset/', UserPasswordResetView.as_view(), name='password_reset'),
    path('password_sent_email/', cache_page(3600)(UserSentPassword.as_view()), name='password_sent_email'),
    path('change_active/<int:pk>/', UserChangeActive.as_view(), name='user_change_active'),
]

PycharmProjects/pythonProject3/catalog/models.py
from django.conf import settings
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    name = models.CharField(max_length=150, verbose_name='Наименование')
    description = models.TextField(max_length=350, verbose_name='Описание')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Product(models.Model):
    name = models.CharField(max_length=150, verbose_name='Наименование')
    description = models.TextField(max_length=500, verbose_name='Описание')
    photo = models.ImageField(upload_to='products/', **NULLABLE, verbose_name='Изображение')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
    price = models.IntegerField(**NULLABLE, verbose_name='Цена за покупку')
    creation = models.DateField(**NULLABLE, verbose_name='Дата создания')
    last_change = models.DateField(**NULLABLE, verbose_name='Дата последнего изменения')

    creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE, verbose_name='Создатель')


    def __str__(self):
        return f'{self.name} ({self.category})'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'
        ordering = ('name',)


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Наименование')
    num = models.IntegerField(**NULLABLE, verbose_name='Номер версии')
    name = models.CharField(max_length=150, verbose_name='Название версии')
    is_active = models.BooleanField(default=True, verbose_name='Текущая версия')

    def __str__(self):
        return f'{self.product} ({self.name})'

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'

PycharmProjects/pythonProject3/catalog/forms.py
from django import forms

from catalog.models import Product, Version


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        exclude = ('creator',)

    def clean_name(self):
        bad_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']
        cleaned_data = self.cleaned_data.get('name')
        for word in bad_words:
            if word in cleaned_data.lower():
                raise forms.ValidationError('Запрещенное название')
        return cleaned_data


class VersionForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Version
        fields = '__all__'

PycharmProjects/pythonProject3/catalog/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.cache import cache
from django.forms import inlineformset_factory
from django.http import Http404
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, TemplateView, DetailView

from catalog.forms import ProductForm, VersionForm
from catalog.models import Category, Product, Version
from catalog.services import get_category_cache


def con(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(f"{name} ({phone}):{message}")
    return render(request, 'catalog/contacts.html')


class IndexView(LoginRequiredMixin, TemplateView):
    template_name = 'catalog/index.html'
    extra_context = {
        'title': 'Главная'
    }

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['object_list'] = Category.objects.all()[:3]
        return context_data


# def home(request):
#     context = {
#         'object_list': Category.objects.all()[:3],
#         'title': 'Главная',
#     }
#     return render(request, 'catalog/index.html', context)

# def categories(request):
#     context = {
#         'object_list': Category.objects.all(),
#         'title': 'Все категории',
#     }
#     return render(request, 'catalog/category_list.html', context)


class CategoryListView(LoginRequiredMixin, ListView):

    model = Category
    extra_context = {
        'object_list' : get_category_cache(),
        'title': 'Все категории'
    }




# def products(request, pk):
#     category_item = Category.objects.get(pk=pk)
#     context = {
#         'object_list': Product.objects.filter(category_id=pk, creator=request.user),
#         'title': f'Товар категории {category_item.name}',
#     }
#     return render(request, 'catalog/product_list.html', context)

class ProductListView(LoginRequiredMixin, ListView):
    model = Product

    def get_queryset(self):
        queryset = super().get_queryset().filter(category_id=self.kwargs.get('pk'))

        if not self.request.user.is_staff:
            queryset = queryset.filter(creator=self.request.user)

        return queryset

    def get_context_data(self, *args, **kwargs):
        category_item = Category.objects.get(pk=self.kwargs.get('pk'))
        context_data = super().get_context_data(*args, **kwargs)
        context_data['category_pk'] = category_item.pk
        context_data['title'] = f'Товар категории {category_item.name}'

        return context_data


class ProductCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    permission_required = 'catalog.add_product'
    success_url = reverse_lazy('catalog:categories')
    extra_context = {
        'title': 'Добавить товар',
    }

    def form_valid(self, form):
        self.object = form.save()
        self.object.creator = self.request.user
        self.object.save()
        
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:home')
    extra_context = {
        'title': 'Изменить товар',
    }

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.creator != self.request.user and not self.request.user.is_staff:
            raise Http404
        return self.object
    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            formset = VersionFormset(self.request.POST, instance=self.object)
        else:
            formset = VersionFormset(instance=self.object)
        context_data['formset'] = formset
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:categories')
    extra_context = {
        'title': 'Удалить товар',
    }

PycharmProjects/pythonProject3/catalog/templates/catalog/categories.html
{% extends 'catalog/home.html' %}

{% block content %}
<div class="container">
    <div class="row text-center">
        {% for object in object_list %}
            {% include 'catalog/includes/inc_category.html' %}
        {% endfor %}
    </div>
</div>

{% endblock %}

PycharmProjects/pythonProject3/catalog/templates/catalog/category_list.html
{% extends 'catalog/home.html' %}

{% block content %}
<div class="container">
    {% if perms.catalog.add_product %}
        <div class="col-12 mb-5">
            <a href="{% url 'catalog:product_create' %}" class="btn btn-primary">Создать товар</a>
        </div>
    {% end if %}
    <div class="row text-center">
        {% for object in object_list %}
            {% include 'catalog/includes/inc_category.html' %}
        {% endfor %}
    </div>
</div>

{% endblock %}

PycharmProjects/pythonProject3/catalog/templates/catalog/contacts.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Продуктовый</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>
    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Контактный телефон" required></textarea>
                        </div>
                    </form>
                    <input type="submit">
                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                </div>
            </div>
        </div>
    </div>

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

PycharmProjects/pythonProject3/catalog/templates/catalog/home.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{title}}</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Пивзалив</h5>
    <nav class="ms-5">
        <a  href="{% url 'catalog:home' %}">Главная</a>
        <a  href="{% url 'catalog:categories' %}">Все категории</a>
        <a  href="/contacts/">Контакты</a>
        <a  href="{% url 'notebook:list' %}">Записи</a>
        {% if user.is_authenticated %}
            <a  href="{% url 'users:profile' %}">Профиль</a>
            <a  href="{% url 'users:logout' %}">Выход</a>
        {% else %}
            <a {# class="p-2 btn btn-outline-primary" #} href="{% url 'users:login' %}">Вход</a>
            <a {# class="p-2 btn btn-outline-primary" #} href="{% url 'users:register' %}">Регистрация</a>
        {% endif %}
    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ title }}</h1>
    <p class="lead">{{ title }}</p>
</div>
{% block content %}
{% endblock %}

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                Пивзалив
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

PycharmProjects/pythonProject3/catalog/templates/catalog/index.html
{% extends 'catalog/home.html' %}

{% block content %}
<div class="container">
    <div class="row text-center">
        {% for object in object_list %}
            {% include 'catalog/includes/inc_category.html' %}
        {% endfor %}
    </div>
</div>

{% endblock %}

PycharmProjects/pythonProject3/catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/index.html' %}

{% block content %}
    <form method="post" class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    Удаление товара
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    <p>Действительно желаете избавиться от товара {{ object.name }}?</p>
                    <button type="submit" class="btn btn-outline-danger">
                        Удалить
                    </button>
                    <a class="btn btn-outline-warning" href="{% url 'catalog:products' object.category.pk %}">Отмена</a>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

PycharmProjects/pythonProject3/catalog/templates/catalog/product_form.html
{% extends 'catalog/index.html' %}

{% block content %}
<form method="post" class="row">
    <div class="col-4">
        <div class="card">
            <div class="card-header">
                {% if object %}
                Редактирование товара
                {% else %}
                Добавление товара
                {% endif %}
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-outline-success">
                    {% if object %}
                    Сохранить
                    {% else %}
                    Добавить
                    {% endif %}
                </button>
            </div>
        </div>
    </div>
    {% if perms.catalog.change_version %}
    <div class="col-4">
        <div class="card">
            <div class="card-header">
                Версия
            </div>
            <div class="card-body">
                {{ formset.management_form }}
                {% for form in formset.forms %}
                {{ form.as_p }}
                {% if forloop.revcounter0 != 0 %}
                <hr>
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
    {% endif %}
</form>
{% endblock %}

PycharmProjects/pythonProject3/catalog/templates/catalog/product_list.html
{% extends 'catalog/home.html' %}
{% load my_tags %}
{% block content %}
<div class="container">
    <div class="row text-center">
        {% for object in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <img class="card-img-top"
                     src="{{ object.photo|mediapath }}"
                     alt="Card image cap">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.name }}</h4>
                </div>
                <div class="card-body">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>{{ object.description }}</li>
                        <li>{{ object.creator|default:"Создано богом" }}</li>
                        <li>{{ Version.object.name }} - {{ Version.object.num }}</li>

                    </ul>
                    <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить за {{ object.price }} рублей</button>
                    <div class="card-footer">
                        <a class="btn btn-link" href="{% url 'catalog:product_update' object.pk %}">Изменить</a>
                        <a class="btn btn-outline-danger" href="{% url 'catalog:product_delete' object.pk %}">Удалить</a>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

PycharmProjects/pythonProject3/catalog/templates/catalog/products.html
{% extends 'catalog/home.html' %}
{% load my_tags %}
{% block content %}
<div class="container">
    <div class="row text-center">
        {% for object in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <img class="card-img-top"
                     src="{{ object.photo|mediapath }}"
                     alt="Card image cap">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.name }}</h4>
                </div>
                <div class="card-body">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>{{ object.description }}</li>

                    </ul>
                    <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}