PycharmProjects/pythonProject3/users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView, UserUpdateView, generate_new_password

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', UserUpdateView.as_view(), name='profile'),
    path('profile/genpassword/', generate_new_password, name='generate_new_password'),
]

mailing_service/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailings.urls', namespace='mailings')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

urls.py
from django.urls import path

from dogs.apps import DogsConfig
from dogs.views import index, categories, category_dogs

app_name = DogsConfig.name

urlpatterns = [
    path('', index, name='index'),
    path('categories/', categories, name='categories'),
    path('<int:pk>/dogs/', category_dogs, name='category_dogs')
]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from django.views.decorators.cache import cache_page

from users.apps import UsersConfig
from users.views import (
    UserRegisterView, UserLoginView, UserSentConfirmEmail, UserConfirmEmailView,
    UserConfirmedEmail, UserFailConfirmEmail, UserPasswordResetView, UserSentPassword,
    UserListView, UserChangeActive, UserDetailView
)

app_name = UsersConfig.name

urlpatterns = [
    path('', UserListView.as_view(), name='user_list'),
    path('user/<int:pk>/', UserDetailView.as_view(), name='user_detail'),
    path('register/', UserRegisterView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('sent_confirm_email/', cache_page(3600)(UserSentConfirmEmail.as_view()), name='email_sent_confirm'),
    path('confirm_email/<str:uidb64>/<str:token>/', UserConfirmEmailView.as_view(), name='email_confirm'),
    path('confirmed_email/', cache_page(3600)(UserConfirmedEmail.as_view()), name='email_confirmed'),
    path('fail_confirm_email/', cache_page(3600)(UserFailConfirmEmail.as_view()), name='email_fail_confirm'),
    path('password_reset/', UserPasswordResetView.as_view(), name='password_reset'),
    path('password_sent_email/', cache_page(3600)(UserSentPassword.as_view()), name='password_sent_email'),
    path('change_active/<int:pk>/', UserChangeActive.as_view(), name='user_change_active'),
]

PycharmProjects/pythonProject3/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from catalog.models import NULLABLE


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='email')
    avatar = models.ImageField(upload_to='users/', verbose_name='аватар', **NULLABLE)
    phone_num = models.CharField(max_length=35, verbose_name='номер телефона', **NULLABLE)
    country = models.CharField(max_length=150, verbose_name='страна', **NULLABLE)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class User(AbstractUser):
    '''
    Класс пользователей сервиса
    '''
    username = None
    email = models.EmailField(max_length=254, verbose_name='e-mail', unique=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

PycharmProjects/pythonProject3/users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from catalog.forms import StyleFormMixin
from users.models import User


class UserRegisterForm(StyleFormMixin, UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserForm(StyleFormMixin, UserChangeForm):

    class Meta:
        model = User
        fields = ('email', 'password', 'first_name', 'last_name', 'phone_num', 'country', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from users.models import User


class RegisterForm(UserCreationForm):
    '''
    Форма регистрации пользователей сервиса
    '''

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2',)


class ResetPasswordForm(forms.Form):
    '''
    Форма сброса пароля
    '''
    email = forms.EmailField(max_length=254, label='e-mail')

    def clean_email(self) -> str:
        cleaned_data = self.cleaned_data['email']
        try:
            user = User.objects.get(email=cleaned_data)
            if not user.is_active:
                raise forms.ValidationError('Пользователь с такими данными не существует или не подтвержден!')
        except User.DoesNotExist:
            raise forms.ValidationError('Пользователь с такими данными не существует или не подтвержден!')

        return cleaned_data

PycharmProjects/pythonProject3/users/views.py
import random

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView as BaseLoginView
from django.contrib.auth.views import LogoutView as BaseLogoutView
from django.core.mail import send_mail
from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView

from users.forms import UserRegisterForm, UserForm
from users.models import User
from users.services import send_new_password


class LoginView(BaseLoginView):
    template_name = 'users/login.html'


class LogoutView(BaseLogoutView):
    pass


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy('users:login')
    template_name = 'users/register.html'

    def form_valid(self, form):
        new_user = form.save()
        send_mail(
            subject='Поздравляем с регистрацией!',
            message='Вы зарегистрировалис на нешем сайте, добро пожаловать!',
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[new_user.email]
        )
        return super().form_valid(form)


class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    success_url = reverse_lazy('users:profile')
    form_class = UserForm
    def get_object(self, queryset=None):
        return self.request.user

@login_required
def generate_new_password(request):
    new_password = ''.join([str(random.randint(0, 9)) for _ in range(12)])
    request.user.set_password(new_password)
    request.user.save()
    send_new_password(request.user.email, new_password)
    return redirect(reverse('catalog:index'))

users/views.py
import string
import random

from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import Group
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.views import LoginView
from django.http import HttpResponse
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse_lazy
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views import View
from django.views.generic import CreateView, TemplateView, ListView, DetailView

from mailings.models import Mailing
from mailings.services import send_email, get_status_object

from typing import Any

from users.forms import RegisterForm, ResetPasswordForm
from users.models import User


class UserRegisterView(UserPassesTestMixin, CreateView):
    '''
    Класс для регистрации пользователей
    '''
    model = User
    template_name = 'users/register.html'
    form_class = RegisterForm
    success_url = reverse_lazy('users:login')

    def form_valid(self, form) -> HttpResponse:
        if form.is_valid():
            self.object = form.save()
            self.object.is_active = False
            self.object.save()

            # генерация токена и uid зарегестрированого пользователя для его дальнейшей активации
            token = default_token_generator.make_token(self.object)
            uid = urlsafe_base64_encode(force_bytes(self.object.id))
            active_url = reverse_lazy('users:email_confirm', kwargs={'uidb64': uid, 'token': token})

            # отправка e-mail сообщения с ссылкой на активацию пользователя
            send_email(
                'Подтверждение e-mail адреса!',
                f'Чтобы подтвердить Ваш e-mail адрес, перейдите по ссылке: http://127.0.0.1:8000{active_url}',
                [self.object.email]
            )

            return redirect('users:email_sent_confirm')

    def get_context_data(self, **kwargs) -> dict[str, Any]:
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Регистрация'

        return context_data

    def test_func(self):
        return self.request.user.is_anonymous


class UserConfirmEmailView(UserPassesTestMixin, View):
    '''
    Класс для подтверждения e-mail адреса
    '''

    def get(self, request, uidb64, token) -> HttpResponse:
        try:
            uid = urlsafe_base64_decode(uidb64)
            user = User.objects.get(pk=uid)
        except:
            user = None

        if user is not None and default_token_generator.check_token(user, token):
            group = Group.objects.get(name='service_users')
            user.groups.add(group)
            user.is_active = True
            user.save()

            return redirect('users:email_confirmed')
        else:
            return redirect('users:email_fail_confirm')

    def test_func(self):
        return self.request.user.is_anonymous


class UserSentConfirmEmail(UserPassesTestMixin, TemplateView):
    '''
    Класс для отображения шаблона с успешной отправкой письма
    '''
    template_name = 'users/email_sent_confirm.html'

    def get_context_data(self, **kwargs) -> dict[str, Any]:
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Письмо отправлено'

        return context_data

    def test_func(self):
        return self.request.user.is_anonymous


class UserConfirmedEmail(UserPassesTestMixin, TemplateView):
    '''
    Класс для отображения шаблона о подтверждении e-mail адреса
    '''
    template_name = 'users/email_confirmed.html'

    def get_context_data(self, **kwargs) -> dict[str, Any]:
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'E-mail подтвержден'

        return context_data

    def test_func(self):
        return self.request.user.is_anonymous


class UserFailConfirmEmail(UserPassesTestMixin, TemplateView):
    '''
    Класс для отображения шаблона об ошибке при подверждение e-mail адреса
    '''
    template_name = 'users/email_fail_confirm.html'

    def get_context_data(self, **kwargs) -> dict[str, Any]:
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Ошибка подтверждения'

        return context_data

    def test_func(self):
        return self.request.user.is_anonymous


class UserLoginView(UserPassesTestMixin, LoginView):
    '''
    Класс для авторизации пользователей
    '''
    template_name = 'users/login.html'

    def get_context_data(self, **kwargs) -> dict[str, Any]:
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Авторизация'

        return context_data

    def test_func(self):
        return self.request.user.is_anonymous


class UserPasswordResetView(UserPassesTestMixin, View):
    '''
    Класс для сброса пароля пользователя сервиса
    '''

    def get(self, request) -> HttpResponse:
        form = ResetPasswordForm

        return render(request, 'users/password_reset_form.html', {'form': form, 'title': 'Сброс пароля'})

    def post(self, request) -> HttpResponse:
        form = ResetPasswordForm(request.POST)

        if form.is_valid():
            user = User.objects.get(email=request.POST.get('email'))
            symbols = string.ascii_letters + string.digits
            password = ''.join(str(random.choice(symbols)) for _ in range(10))
            user.set_password(password)
            user.save()

            send_email(
                'Ваш новый пароль!',
                f'Ваш пароль для входа в систему: {password}',
                [user.email]
            )

            return redirect('users:password_sent_email')

        return render(request, 'users/password_reset_form.html', {'form': form, 'title': 'Сброс пароля'})

    def test_func(self):
        return self.request.user.is_anonymous


class UserSentPassword(UserPassesTestMixin, TemplateView):
    '''
    Класс для отображения шаблона об успешной отправки нового пароля
    '''
    template_name = 'users/password_sent_email.html'

    def get_context_data(self, **kwargs) -> dict[str, Any]:
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Новый пароль отправлен'

        return context_data

    def test_func(self):
        return self.request.user.is_anonymous


class UserListView(LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin, ListView):
    '''
    Класс для просмотра всех пользователей сервиса
    '''
    model = User
    permission_required = 'users.view_user'

    def get_context_data(self, **kwargs) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['title'] = 'Пользователи'

        return context

    def test_func(self) -> bool:
        return self.request.user.is_staff


class UserDetailView(LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin, DetailView):
    '''
    Класс для просмотра одного пользователя сервиса
    '''
    model = User
    permission_required = 'users.view_user'

    def get_context_data(self, **kwargs) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        user = self.object

        context['title'] = f'{self.object.email}'
        context['total_mailings'] = len(Mailing.objects.filter(user=user))
        context['created_mailings'] = len(Mailing.objects.filter(user=user, status=get_status_object('создана')))
        context['running_mailings'] = len(Mailing.objects.filter(user=user, status=get_status_object('запущена')))
        context['user'] = self.request.user

        return context

    def test_func(self) -> bool:
        return self.request.user.is_staff


class UserChangeActive(LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin, View):
    '''
    Класс для изменения поля is_active у пользователя сервиса
    '''
    permission_required = 'users.change_user'

    def __get_user(self, pk) -> User:
        user = get_object_or_404(User, pk=pk)

        return user

    def get(self, request, pk) -> HttpResponse:
        user = self.__get_user(pk)

        if user.is_active:
            title = 'Блокировка пользователя'
        else:
            title = 'Разблокировка пользователя'

        return render(request, 'users/user_change_active.html', {'object': user, 'title': title})

    def post(self, request, pk) -> HttpResponse:
        user = self.__get_user(pk)

        if user.is_active:
            user.is_active = False
            for mailing in user.mailing_set.all():
                mailing.status = get_status_object('завершена')
                mailing.save()
        else:
            user.is_active = True

        user.save()

        return redirect('users:user_list')

    def test_func(self) -> bool:
        return self.request.user.is_staff

users/templates/users/email_confirmed.html
{% extends 'mailings/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container mt-4">
    <div class="row">
        <div class="card">
            <div class="card-title text-start">
                <h3 class="p-2 mt-1 ms-2">E-mail адрес подтвержден!</h3>
            </div>
            <div class="card-body">
                <p class="fs-5">Вы успешно подтвердили свой почтовый ящик!</p>
                <a href="{% url 'users:login' %}" class="btn btn-dark">Войти в аккаунт</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/email_fail_confirm.html
{% extends 'mailings/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container mt-4">
    <div class="row">
        <div class="card">
            <div class="card-title text-start">
                <h3 class="p-2 mt-1 ms-2">Ошибка подтверждения e-mail адреса!</h3>
            </div>
            <div class="card-body">
                <p class="fs-5">Во время подтверждения e-mail адреса произошла ошибка!</p>
                <p class="text-muted">Ссылка устарела или в данный момент происходят неполадки на
                    сервере! Пожалуйста, попробуйте позднее!</p>
                <a href="{% url 'mailings:index' %}" class="btn btn-dark">На главную</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/email_sent_confirm.html
{% extends 'mailings/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container mt-4">
    <div class="row">
        <div class="card">
            <div class="card-title text-start">
                <h3 class="p-2 mt-1 ms-2">Подтверждение e-mail адреса</h3>
            </div>
            <div class="card-body">
                <p class="fs-5">На ваш почтовый ящик было отправлено письмо с подтверждением!</p>
                <p class="text-muted">Перейдите по ссылке в письме, чтобы подтвердить аккаунт.</p>
                <a href="{% url 'mailings:index' %}" class="btn btn-dark">На главную</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/login.html
{% extends 'mailings/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container mt-4">
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <form method="post" enctype="multipart/form-data">
                <div class="row">
                    <div class="card">
                        <div class="card-title text-center"><h3 class="p-2">АВТОРИЗАЦИЯ</h3></div>
                        <div class="card-body">
                            {% csrf_token %}
                            {{ form|crispy }}
                            <div class="row">
                                <div class="col-4">
                                    <button type="submit" class="btn btn-outline-dark mt-4">ВОЙТИ</button>
                                </div>
                                <div class="col-4"></div>
                                <div class="col-4 mt-5 text-end">
                                    <a href="{% url 'users:password_reset' %}">забыли пароль?</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/password_reset_form.html
{% extends 'mailings/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container mt-4">
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <form method="post" enctype="multipart/form-data">
                <div class="row">
                    <div class="card">
                        <div class="card-title text-center"><h3 class="p-2">ВОССТАНОВЛЕНИЕ ПАРОЛЯ</h3></div>
                        <div class="card-body">
                            {% csrf_token %}
                            {{ form|crispy }}
                            <div class="row">
                                <div class="col-4">
                                    <button type="submit" class="btn btn-outline-dark mt-4">ВОССТАНОВИТЬ</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/password_sent_email.html
{% extends 'mailings/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container mt-4">
    <div class="row">
        <div class="card">
            <div class="card-title text-start">
                <h3 class="p-2 mt-1 ms-2">Ваш новый пароль успешно отправлен!</h3>
            </div>
            <div class="card-body">
                <p class="fs-5">На ваш почтовый ящик был отправлен новый пароль для входа в систему!</p>
                <p class="text-muted">Получите новый пароль на вашем почтовом ящике и введите его при
                    следующем входе в систему.</p>
                <a href="{% url 'users:login' %}" class="btn btn-dark">Войти в аккаунт</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'mailings/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container mt-4">
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <form method="post" enctype="multipart/form-data">
                <div class="row">
                    <div class="card">
                        <div class="card-title text-center"><h3 class="p-2">РЕГИСТРАЦИЯ</h3></div>
                        <div class="card-body">
                            {% csrf_token %}
                            {{ form|crispy }}
                            <div class="row">
                                <div class="col-4">
                                    <button type="submit" class="btn btn-outline-dark mt-4">СОЗДАТЬ АККАУНТ</button>
                                </div>
                                <div class="col-4"></div>
                                <div class="col-4 mt-5">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/user_change_active.html
{% extends 'mailings/base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <form method="post" class="card">
            {% csrf_token %}
            {% if object.is_active %}
                <h2>Вы действительно хотите заблокировать пользователя "{{ object.email }}"?</h2>
                <p class="mb-3 fw-semibold lh-1 mt-3">Вы также сможете его разблокировать позже.</p>
            {% else %}
                <h2>Вы действительно хотите разблокировать пользователя "{{ object.email }}"?</h2>
                <p class="mb-3 fw-semibold lh-1 mt-3">Вы также сможете его заблокировать позже.</p>
            {% endif %}
            <div class="row mt-1 mb-2">
                <div class="col-1 me-5 ">
                    <button type="submit" class="btn btn-outline-dark">
                        {% if object.is_active %}
                            ЗАБЛОКИРОВАТЬ
                        {% else %}
                            РАЗБЛОКИРОВАТЬ
                        {% endif %}
                    </button>
                </div>
                {% if object.is_active %}
                    <div class="col-1 ms-2">
                        <a class="btn btn-outline-dark" href="{% url 'users:user_list' %}">НАЗАД</a>
                    </div>
                {% else %}
                    <div class="col-1 ms-3">
                        <a class="btn btn-outline-dark" href="{% url 'users:user_list' %}">НАЗАД</a>
                    </div>
                {% endif %}
            </div>
        </form>
    </div>
</div>
{% endblock %}

users/templates/users/user_detail.html
{% extends 'mailings/base.html' %}

{% block content %}

<div class="container">
    <div class="row">
        <h1 class="mt-2 text-center">ИНФОРМАЦИЯ О ПОЛЬЗОВАТЕЛЕ</h1>
        <div class="card mt-2">
            <div class="card-title">
                <h3 class="p-1"><b>E-mail адрес:</b> {{ object.email }}</h3>
            </div>
            <hr>
            <div class="card-body">
                <p class="fs-5"><b>Всего рассылок: </b>{{ total_mailings }}
                <p class="fs-5"><b>Созданных рассылок: </b>{{ created_mailings }}</p>
                <p class="fs-5"><b>Запущенных рассылок: </b>{{ running_mailings }}</p>
                <div class="row">
                    <div class="col-10"></div>
                    <div class="col-2 text-end">
                        {% if object.is_active %}
                            <a href="{% url 'users:user_change_active' object.id%}" type="button"
                           class="btn btn-outline-dark mb-2">Заблокировать</a>
                        {% else %}
                            <a href="{% url 'users:user_change_active' object.id%}" type="button"
                               class="btn btn-outline-dark mb-2">Разблокировать</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/user_list.html
{% extends 'mailings/base.html' %}

{% block content %}
<div class="container text-center mt-5 mb-5">
    <h1 class="mt-5">ПОЛЬЗОВАТЕЛИ</h1>
    <div class="row mt-4">
        {% for object in object_list %}
            {% if object.is_active %}
                <div class="col-3">
                    <a href="{% url 'users:user_detail' object.pk %}" class="text-white">
                        <div class="card text-white bg-dark mb-3" style="max-width: 18rem;">
                            <div class="card-header mt-2">{{ object.email }}</div>
                            <hr>
                            <a href="{% url 'users:user_change_active' object.id%}" type="button"
                               class="btn btn-dark mb-2">Заблокировать</a>
                        </div>
                    </a>
                </div>
            {% endif %}
        {% endfor %}
        <hr>
        {% for object in object_list %}
            {% if not object.is_active %}
                <div class="col-3">
                    <a href="{% url 'users:user_detail' object.pk %}" class="link-light">
                        <div class="card text-white bg-white mb-3" style="max-width: 18rem;">
                            <div class="card-header mt-2 text-dark">{{ object.email }}</div>
                            <hr>
                            <a href="{% url 'users:user_change_active' object.id%}" type="button"
                               class="btn btn-light mb-2">Разблокировать</a>
                        </div>
                    </a>
                </div>
            {% endif %}
        {% endfor %}
    </div>
</div>
{% endblock %}