PycharmProjects/pythonProject3/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('notebook/', include('notebook.urls', namespace='notebook')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from blog.apps import BlogConfig
from blog.views import (
    ArticleListView, ArticleDetailView, ArticleCreateView, ArticleUpdateView, ArticleDeleteView
)

from django.urls import path

app_name = BlogConfig.name

urlpatterns = [
    path('articles/', ArticleListView.as_view(), name='article_list'),
    path('articles/<int:pk>/', ArticleDetailView.as_view(), name='article_detail'),
    path('create_article/', ArticleCreateView.as_view(), name='article_create'),
    path('update_article/<int:pk>/', ArticleUpdateView.as_view(), name='article_update'),
    path('delete_article/<int:pk>/', ArticleDeleteView.as_view(), name='article_delete'),
]

mailing_service/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailings.urls', namespace='mailings')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

mailings/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mailings.apps import MailingsConfig
from mailings.views import (
    IndexView, MailingListView, MailingDetailView, MailingCreateView,
    MailingUpdateView, MailingDeleteView, ChangeMailingStatusView, ClientListView,
    ClientDetailView, ClientCreateView, ClientUpdateView, ClientDeleteView,
    MailingLogsListView, ManagerMailingListView
)

app_name = MailingsConfig.name

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('mailings/', MailingListView.as_view(), name='mailing_list'),
    path('mailings/<slug:slug>/', MailingDetailView.as_view(), name='mailing_detail'),
    path('mailing_create/', MailingCreateView.as_view(), name='mailing_create'),
    path('mailing_update/<slug:slug>/', MailingUpdateView.as_view(), name='mailing_update'),
    path('mailing_delete/<slug:slug>/', MailingDeleteView.as_view(), name='mailing_delete'),
    path('status_change/<slug:slug>/', ChangeMailingStatusView.as_view(), name='mailing_status'),
    path('clients/', ClientListView.as_view(), name='client_list'),
    path('clients/<int:pk>/', cache_page(900)(ClientDetailView.as_view()), name='client_detail'),
    path('client_create/', ClientCreateView.as_view(), name='client_create'),
    path('client_update/<int:pk>/', ClientUpdateView.as_view(), name='client_update'),
    path('client_delete/<int:pk>/', ClientDeleteView.as_view(), name='client_delete'),
    path('mailing_logs/', MailingLogsListView.as_view(), name='mailing_logs_list'),
    path('manager_mailing/', ManagerMailingListView.as_view(), name='manager_mailing_list'),
]

urls.py
from django.urls import path

from dogs.apps import DogsConfig
from dogs.views import index, categories, category_dogs

app_name = DogsConfig.name

urlpatterns = [
    path('', index, name='index'),
    path('categories/', categories, name='categories'),
    path('<int:pk>/dogs/', category_dogs, name='category_dogs')
]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from django.views.decorators.cache import cache_page

from users.apps import UsersConfig
from users.views import (
    UserRegisterView, UserLoginView, UserSentConfirmEmail, UserConfirmEmailView,
    UserConfirmedEmail, UserFailConfirmEmail, UserPasswordResetView, UserSentPassword,
    UserListView, UserChangeActive, UserDetailView
)

app_name = UsersConfig.name

urlpatterns = [
    path('', UserListView.as_view(), name='user_list'),
    path('user/<int:pk>/', UserDetailView.as_view(), name='user_detail'),
    path('register/', UserRegisterView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('sent_confirm_email/', cache_page(3600)(UserSentConfirmEmail.as_view()), name='email_sent_confirm'),
    path('confirm_email/<str:uidb64>/<str:token>/', UserConfirmEmailView.as_view(), name='email_confirm'),
    path('confirmed_email/', cache_page(3600)(UserConfirmedEmail.as_view()), name='email_confirmed'),
    path('fail_confirm_email/', cache_page(3600)(UserFailConfirmEmail.as_view()), name='email_fail_confirm'),
    path('password_reset/', UserPasswordResetView.as_view(), name='password_reset'),
    path('password_sent_email/', cache_page(3600)(UserSentPassword.as_view()), name='password_sent_email'),
    path('change_active/<int:pk>/', UserChangeActive.as_view(), name='user_change_active'),
]

mailings/forms.py
from datetime import datetime

from django import forms

from mailings.models import Mailing, Client


class MailingForm(forms.ModelForm):
    '''
    Форма рассылки сервиса
    '''

    class Meta:
        model = Mailing
        fields = ('title', 'body', 'sending_time', 'regularity',)
        widgets = {'sending_time': forms.DateTimeInput(attrs={'type': 'datetime-local'})}

    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self.fields['sending_time'].help_text = 'Рассылка должна быть опубликована не ранее, ' \
                                                'чем через минуту от текущего времени.'

    def clean_sending_time(self) -> datetime:
        cleaned_data = self.cleaned_data['sending_time']

        if cleaned_data.timestamp() <= datetime.now().timestamp():
            raise forms.ValidationError('Рассылка должна иметь достоверное время')

        return cleaned_data


class ClientForm(forms.ModelForm):
    '''
    Форма клиента сервиса
    '''

    class Meta:
        model = Client
        fields = ('fullname', 'email', 'comment',)

    def __init__(self, *args, **kwargs) -> None:
        self.user = kwargs.pop('user')
        self.email = kwargs.pop('email')

        super().__init__(*args, **kwargs)

    def clean_email(self) -> str:
        cleaned_data = self.cleaned_data['email']

        if cleaned_data != self.email:
            is_existed = Client.objects.filter(email=cleaned_data, user=self.user).exists()

            if is_existed:
                raise forms.ValidationError('Пользователь с таким e-mail существует!')

        return cleaned_data

mailings/views.py
import random

from django.contrib.auth.mixins import (
    LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
)
from django.db.models import Q, QuerySet
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import (
    CreateView, DeleteView, DetailView, ListView, TemplateView, UpdateView
)

from typing import Any

from pytils.translit import slugify

from mailings.forms import ClientForm, MailingForm
from mailings.models import Client, Mailing, MailingLogs, MailingStatus
from mailings.services import (
    check_mailing_status, check_user, get_articles_from_cache, get_status_object
)


class IndexView(TemplateView):
    '''
    Класс отображения главной страницы сервиса
    '''
    template_name = 'mailings/index.html'

    def get_context_data(self, **kwargs) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['title'] = 'Главная страница'
        context['total_mailings'] = len(Mailing.objects.all())
        context['active_mailings'] = len(Mailing.objects.exclude(status=get_status_object('завершена')))
        context['unique_clients'] = len(Client.objects.values('email').distinct())
        try:
            context['blog_articles'] = random.sample(list(get_articles_from_cache()), 3)
        except ValueError:
            context['blog_articles'] = []

        return context


class MailingListView(LoginRequiredMixin, UserPassesTestMixin, PermissionRequiredMixin, ListView):
    '''
    Класс отображения страницы со всеми рассылками
    '''
    model = Mailing
    permission_required = 'mailings.view_mailing'

    def get_queryset(self, *args, **kwargs) -> QuerySet:
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(user=self.request.user)

        return queryset

    def get_context_data(self, **kwargs) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['title'] = 'Рассылки'

        return context

    def test_func(self) -> bool:
        return self.request.user.groups.filter(name='service_users')


class MailingDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    '''
    Класс для отображения информации об одной рассылке
    '''
    model = Mailing
    permission_required = 'mailings.view_mailing'

    def dispatch(self, request, *args, **kwargs) -> HttpResponse:
        group = self.request.user.groups.filter(name='manager')
        status = self.get_object().status

        if not group:
            if not check_user(self.get_object().user, self.request.user):
                return redirect('mailings:mailing_list')
        else:
            if status == get_status_object('завершена'):
                return redirect('mailings:manager_mailing_list')

        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['title'] = self.object.title

        return context


class MailingCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    '''
    Класс для создания рассылки
    '''
    model = Mailing
    form_class = MailingForm
    permission_required = 'mailings.add_mailing'
    success_url = reverse_lazy('mailings:mailing_list')

    def form_valid(self, form) -> HttpResponse:
        if form.is_valid():
            self.object = form.save()
            self.object.status = MailingStatus.objects.get(name='создана')
            self.object.slug = slugify(f'{self.object.title}-{self.object.pk}')
            self.object.user = self.request.user
            self.object.save()

        return super().form_valid(form)

    def get_context_data(self, **kwargs) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['title'] = 'Создание рассылки'

        return context


class MailingUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    '''
    Класс для редактирования рассылки
    '''
    model = Mailing
    form_class = MailingForm
    permission_required = 'mailings.change_mailing'
    success_url = reverse_lazy('mailings:mailing_list')

    def dispatch(self, request, *args, **kwargs) -> HttpResponse:
        mailing = self.get_object()

        if not check_user(mailing.user, self.request.user) or not check_mailing_status(mailing, 'создана'):
            return redirect('mailings:mailing_list')

        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form) -> HttpResponse:
        if form.is_valid():
            self.object = form.save()
            self.object.slug = slugify(f'{self.object.title}-{self.object.pk}')
            self.object.save()

        return super().form_valid(form)

    def get_context_data(self, **kwargs) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['title'] = f'Редактирование рассылки {self.object.title}'

        return context


class MailingDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    '''
    Класс для удаления рассылки
    '''
    model = Mailing
    permission_required = 'mailings.delete_mailing'

    def dispatch(self, request, *args, **kwargs) -> HttpResponse:
        mailing = self.get_object()
        group = self.request.user.groups.filter(name='manager')

        if not group:
            if not check_user(mailing.user, self.request.user) or check_mailing_status(mailing, 'запущена'):
                return redirect('mailings:mailing_list')
        elif self.get_object().status != get_status_object('создана'):
            return redirect('mailings:manager_mailing_list')

        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self) -> str:
        group = self.request.user.groups.filter(name='manager')

        if group:
            return reverse('mailings:manager_mailing_list')

        return reverse('mailings:mailing_list')

    def get_context_data(self, **kwargs) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['title'] = f'Удаление рассылки {self.object.title}'

        return context


class ChangeMailingStatusView(LoginRequiredMixin, PermissionRequiredMixin, View):
    '''
    Класс для перевода рассылки к типу "завершена"
    '''
    permission_required = 'mailings.change_mailingstatus'

    def __get_mailing(self, slug) -> Mailing:
        mailing = get_object_or_404(Mailing, slug=slug)

        return mailing

    def get(self, request, slug) -> HttpResponse:
        mailing = self.__get_mailing(slug)
        group = self.request.user.groups.filter(name='manager')

        if not group:
            if not check_user(mailing.user, self.request.user) or not check_mailing_status(mailing, 'запущена'):
                return redirect('mailings:mailing_list')
        elif not check_mailing_status(mailing, 'запущена'):
            return redirect('mailings:manager_mailing_list')

        return render(
            request, 'mailings/mailing_status_change.html',
            {'object': mailing, 'title': 'Изменение статуса'}
        )

    def post(self, request, slug) -> HttpResponse:
        mailing = self.__get_mailing(slug)
        mailing.status = MailingStatus.objects.get(name='завершена')
        mailing.save()

        group = self.request.user.groups.filter(name='manager')

        if group:
            return redirect('mailings:manager_mailing_list')

        return redirect('mailings:mailing_list')


class ClientListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    '''
    Класс для отображения всех клиентов
    '''
    model = Client
    permission_required = 'mailings.view_client'

    def get_queryset(self, *args, **kwargs) -> QuerySet:
        queryset = super().get_queryset(*args, **kwargs)
        user = self.request.user
        queryset = queryset.filter(user=user)

        return queryset

    def get_context_data(self, **kwargs) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['title'] = 'Клиенты'

        return context


class ClientDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    '''
    Класс для отображения одного клиента
    '''
    model = Client
    permission_required = 'mailings.view_client'

    def dispatch(self, request, *args, **kwargs) -> HttpResponse:
        if not check_user(self.get_object().user, self.request.user):
            return redirect('mailings:client_list')

        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['title'] = self.object.fullname

        return context


class ClientCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    '''
    Класс для создания клиента
    '''
    model = Client
    form_class = ClientForm
    permission_required = 'mailings.add_client'
    success_url = reverse_lazy('mailings:client_list')

    def get_form_kwargs(self) -> dict[str, Any]:
        kwargs = super().get_form_kwargs()
        kwargs.update({'user': self.request.user, 'email': None})

        return kwargs

    def form_valid(self, form) -> HttpResponse:
        if form.is_valid():
            self.object = form.save()
            self.object.user = self.request.user
            self.object.save()

        return super().form_valid(form)

    def get_context_data(self, **kwargs) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['title'] = 'Создание клиента'

        return context


class ClientUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    '''
    Класс для обновления клиента
    '''
    model = Client
    form_class = ClientForm
    permission_required = 'mailings.change_client'

mailings/templates/mailings/includes/inc_footer.html
{% load custom_tags %}

<div class="container">
    <footer class="py-3 my-4">
        <ul class="nav justify-content-center border-bottom pb-3 mb-3">
            <li class="nav-item"><a href="{% url 'mailings:index' %}" class="nav-link px-2 text-muted">Главная</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Блог</a></li>
            {% if user.is_authenticated %}
                {% if user|has_group:"service_users" %}
                    <li class="nav-item">
                        <a href="{% url 'mailings:mailing_list' %}" class="nav-link px-2 text-muted">Рассылки</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'mailings:client_list' %}" class="nav-link px-2 text-muted">Клиенты</a>
                    </li>
                {% endif %}
                {% if user|has_group:"manager" %}
                    <li class="nav-item">
                        <a href="{% url 'users:user_list' %}" class="nav-link px-2 text-muted">Пользователи</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'mailings:manager_mailing_list' %}" class="nav-link px-2 text-muted">Рассылки</a>
                    </li>
                {% endif %}
                    <li class="nav-item">
                        <a href="{% url 'users:logout' %}" class="nav-link px-2 text-muted">Выйти</a>
                    </li>
                {% if user.is_superuser %}
                    <li class="nav-item">
                        <a href="{% url 'admin:index' %}" class="nav-link px-2 text-muted">Админка</a>
                    </li>
                {% endif %}
            {% else %}
                <li class="nav-item">
                    <a href="{% url 'users:login' %}" class="nav-link px-2 text-muted">Войти</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'users:register' %}" class="nav-link px-2 text-muted">Создать аккаунт</a>
                </li>
            {% endif %}
        </ul>
        <p class="text-center text-muted">© {% now 'Y' %} SEND BAND</p>
    </footer>
</div>

mailings/templates/mailings/includes/inc_main_menu.html
{% load custom_tags %}

<div class="container">
    <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'mailings:index' %}">SEND BAND</a>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'mailings:index' %}">Главная</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'blog:article_list' %}">Блог</a>
                    </li>
                    {% if user.is_authenticated %}
                        {% if user|has_group:"service_users" %}
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'mailings:mailing_list' %}">
                                    Рассылки
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'mailings:client_list' %}">
                                    Клиенты
                                </a>
                            </li>
                        {% endif %}
                        {% if user|has_group:"manager" %}
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'users:user_list' %}">
                                    Пользователи
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page"
                                   href="{% url 'mailings:manager_mailing_list' %}">
                                    Рассылки
                                </a>
                            </li>
                        {% endif %}
                        <li class="nav-item">
                            <a class="nav-link active ms-5" aria-current="page" href="{% url 'users:logout' %}">
                                Выйти
                            </a>
                        </li>
                        {% if user.is_superuser %}
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'admin:index' %}">
                                    Админка
                                </a>
                            </li>
                        {% endif %}
                    {% else %}
                        <li class="nav-item ms-10">
                            <a class="nav-link active ms-5" aria-current="page" href="{% url 'users:login' %}">
                                Войти
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'users:register' %}">
                                Создать аккаунт
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <hr>
</div>